setClass("hypredGenome",
         representation(num.chr = "integer",
                        len.chr = "numeric",
                        num.snp.chr = "integer",
                        pos.snp = "numeric",
                        pos.snp.block = "numeric",
                        block.info = "list",
                        chr.break.pts = "matrix",
                        num.add.qtl.chr = "integer",
                        num.dom.qtl.chr = "integer",
                        pos.add.qtl = "list",
                        pos.dom.qtl = "list",
                        add.and.dom.eff = "list",
                        num.per.mar.chr = "integer",
                        per.mar.id = "integer"))
